### ISSUE TITLE
Publish on packagist

### ISSUE THREAD

**Issue by ewinslow** [hypeJunction/hypeFaker#1]
I see you have a composer.json and you're at a stable version (1.0.2), but when I try to include with `composer require --dev hypejunction/hypefaker:^1.0.2` I get no love.

Seems super handy, but I'm pretty much over manually installing plugins now :)

**Comment by hypeJunction** [comment]
I am quite sure I published it. Will double check. packagist seems down at the moment...

**Comment by ewinslow** [comment]
Thanks for looking into it. I see a lot of hypeJunction packages but no hypejunction/hypefaker

**Comment by hypeJunction** [comment]
You should be good to go

**Comment by ewinslow** [comment]
Thanks!
